name: mongo_ai
description: "깃협업 연습을 위한 메모앱"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  cupertino_icons: ^1.0.8
  
  # 모델링
  json_annotation: ^4.9.0

  # 라우팅
  go_router: ^15.1.1
  
  # 간격
  gap: ^3.0.1
  
  # 저장소
  hive: ^2.2.3 # 로컬
  supabase_flutter: ^2.8.4 # 원격

  # UUID 생성(RFC4122 아니면 RFC9562)
  uuid: ^4.5.1

  # 권한 설정
  permission_handler: ^12.0.0+1

  # 키 값 관리
  freezed_annotation: ^3.0.0

  # 파일 처리
  image_picker: ^1.1.2
  file_picker: ^10.1.2

  # 상태관리
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # 경로 기반 URL 전략
  flutter_web_plugins:
    sdk: flutter

  printing: ^5.11.1
  # .env 파일
  flutter_dotenv: ^5.2.1

  #PDF 생성
  pdf: ^3.11.3

  # 점선 그리기
  dotted_border: ^2.1.0

  # DateTime 포맷 변경
  intl: ^0.20.2

  # OTP 인증 핀 입력
  pinput: ^3.0.1

  # json 애니메이션
  lottie: ^2.3.0

  # 반응형 그리드뷰 그리기
  responsive_grid_list: ^1.4.0

  # 파일 드래그해서 넣기
  flutter_dropzone: ^4.2.1
  
  # badge 추가를 위한 패키지
  badges: ^3.1.2

  # 로딩 인디케이터
  flutter_spinkit: ^5.2.1

  # firebase
  firebase_core: ^3.13.0
  firebase_analytics: ^11.4.5

  # Google Sign In
  google_sign_in: ^6.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

  # Mocking 패키지
  mockito: ^5.4.5

  # Dart Test
  test: ^1.25.15

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
