name: mongo_ai
description: "깃협업 연습을 위한 메모앱"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  cupertino_icons: ^1.0.8
  
  # 모델링
  json_annotation: ^4.9.0

  # 라우팅
  go_router: ^15.1.1
  
  # 간격
  gap: ^3.0.1
  
  # 저장소
  hive: ^2.2.3 # 로컬
  supabase_flutter: ^2.8.4 # 원격

  # UUID 생성(RFC4122 아니면 RFC9562)
  uuid: ^4.5.1

  # 권한 설정
  permission_handler: ^12.0.0+1

  # 키 값 관리
  freezed_annotation: ^3.0.0

  # 파일 처리
  image_picker: ^1.1.2
  file_picker: ^10.1.2

  # 상태관리
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # 경로 기반 URL 전략
  flutter_web_plugins:
    sdk: flutter

  printing: ^5.11.1
  # .env 파일
  flutter_dotenv: ^5.2.1

  #PDF 생성
  pdf: ^3.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
flutter:
  uses-material-design: true
  assets:
    - .env

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
